### ISSUE TITLE
White theme?

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#1]
I'm not to fond of the black style. Every other fields are white. Maybe an option, or just make it white?

**Comment by molocLab** [comment]
The reason is simple, it has the same style of the calendar that appear using date field.

**Comment by jenstornell** [comment]
There are two differences I think:

1. Size. Date field is small and don't create a big black hole in the panel.
1. Popup. Inline fields are white. Date is a popup field and popups are black. This plugin is not a popup.

If you don't want to change this it's ok. It's not a bug and it's not very hard to change the CSS for anyone who needs to.

![image](https://cloud.githubusercontent.com/assets/927011/12674991/8031c940-c687-11e5-9f6f-0313ceb0d10d.png)

**Comment by molocLab** [comment]
It's a good argumentation.... I'll think about it.

I don't close the issue for now.

**Comment by jenstornell** [comment]
I can just add to this that elements inside other elements also get black. In the screenshot below the tabs are black but the main element is white. That rule also work for the calendar popup, where the popup / subelement is black and the main element is white.

https://getkirby.imgix.net/content/home/hero/slide-01.png

**Comment by molocLab** [comment]
Something like that?

![calendar](https://cloud.githubusercontent.com/assets/11831276/12747502/a23f4786-c9a4-11e5-96ca-57ff5a780e77.png)

**Comment by jenstornell** [comment]
Awesome! Looks very much like I expected.

The only concern I have is the information added in the black boxes. I liked the feature of put any kind of fields in the structure field. Is that still the case?

1. How is the content rendered in the black boxes?
1. What will happen if there are 10 events in the same day? Does it break?

**Comment by molocLab** [comment]
I'm just playing with this feature.
The idea is to display some event informations stored in the structure field.
These informations are managed through an option in the blueprint:

```
  calendar:
    label: Calendar
    type:  calendarboard
    spoilers: info1,info2
```

When the day space is totally occupied, simply it displays the first 4/5 events and then print a more ("...") icon.

**Comment by jenstornell** [comment]
Just what I was hoping for on both the questions.

The text can also be too wide. Maybe you can use `text-overflow: ellipsis;` on that?

http://www.w3schools.com/cssref/tryit.asp?filename=trycss3_text-overflow

**Comment by molocLab** [comment]
Exactly. I think it's not important to see the whole information.
They have to be just spoilers of what the user will find in the detail page.

**Comment by jenstornell** [comment]
Agree. I hope that `ìnfo1` and `info2` are connected as keys to the structure field to get the values? I just took that for granted.

Another thing comes to my mind. If I want to get what cottages are booked I could get values like `1` or `2` (cottages names). It's not possible to see what kind of data 1 and 2 is.

Maybe something like this?

```yaml
spoilers: Cottage: [info1]. Type: [info2]
```

where the content inside brackets are replaced with values? It's probably not allowed to add colon after cottage as I did so I see some problems with my solution.

Maybe an array instead with key / value pairs?

Or instead have a link to a snippet where the user can format the output.

I'm just thinking out loud. Right now I feel like a key / value pair array would be best.

**Comment by jenstornell** [comment]
I moved the spoiler discussion to a new issue so we can keep this one to the white theme.

**Comment by molocLab** [comment]
Switched to light theme.

![download](https://cloud.githubusercontent.com/assets/11831276/12880868/2321bb78-ce45-11e5-8367-99a0be2abf50.png)

**Comment by jenstornell** [comment]
Beautiful. I just tried it out and it works great. Looks like a native field now. Close this issue?

**Comment by strukturart** [comment]
Hello,

how show the black boxes with the event title ?
