### ISSUE TITLE
Remove day

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#13]
It seems not possible to remove a day. Remove items from the day structure field works but not to delete the whole day.

Maybe it's just possible to enable "Delete this page" or something by the blueprint of the day?

Else there might be 365 empty days for no reason.

**Comment by molocLab** [comment]
I preferred to disable page deleting by default.
If you want to active this option just remove `deletable: false` in `calendar-board-day.yaml` blueprint.

**Comment by jenstornell** [comment]
Another option would be to hook it and delete the day if the structure field is empty when saved?

**Comment by molocLab** [comment]
No, because in day page you may have other fields in addition to events structure field.

**Comment by jenstornell** [comment]
Ok, then I agree.
