### ISSUE TITLE
Make it more clear where to click on arrows

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#18]
The arrows have no line that shows where they start/end. I clicked outside the arrow by mistake.

**Possible solutions:**

- Add a line between arrows and month name.
- Add a hover effect when over the arrow.
- Some other way to show where the arrow buttons starts/ends.

It's a really small thing, I know.

**Comment by molocLab** [comment]
Hover effect in Kirby panel style added
