### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#23]
```js
function builtCalendar(F,M,Y){
```
..
```js
field_name = $(F).siblings("label.label").attr("for").replace("form-field-", "");
```

> Uncaught TypeError: Cannot read property 'replace' of undefined

It works but when adding other plugins that require js the other plugins fail to load.

**Comment by jenstornell** [comment]
This plugin for example did not work because of it.

https://github.com/afbora/Kirby-Tabs-Field

**Comment by jenstornell** [comment]
This seems to fix it. I don't know if it's only my version or this as well but there you go.

```js
if(typeof F == "string"){
      field_name = F;
    }else{
      label_label = $(F).siblings("label.label");
      if( label_label.attr("for") ) {
        field_name = $(F).siblings("label.label").attr("for").replace("form-field-", "");
      }
    }
```

**Comment by molocLab** [comment]
In the new version I totally refactory this part to avoid these kind of issues.
I will publish it as soon as possible.

**Comment by molocLab** [comment]
Fixed and tested with Kirby Tabs Field
