### ISSUE TITLE
calendar.php collision

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#4]
You have a calendar.php in your field folder. That file will only run in the panel. To make it work on the frontend I added Bastian calendar.php as a plugin. It works fine on the frontend because the field calendar.php will not be loaded.

However, the panel breaks because not both plugin calendar.php and field calendar.php are loaded. Collision.

Solution? If it's unclear, just ask.

**Comment by molocLab** [comment]
Move calendar.php inside snippets folder (it's not real a plugin) and include it in the your project with:
`<?php snippet('calendar') ?>`

I thought to rename calendar library in the custom field with something like "calendar-board-calendar.php", but it is not a my library and I prefer to maintain its original name.

**Comment by jenstornell** [comment]
That's an ok workaround.

You are right, it's not made to be a plugin.

On the other hand, it's not a snippet, because it contains logic and logic should go into a plugin.

For a more solid solution, maybe you can use a namespace on your version of the calendar plugin? It would require one row above the calendar.php so you are not changing much.

Maybe ask Bastian if he is ok with how you are using the class?

**Comment by molocLab** [comment]
Added the namespace and testing using calendar as plugin in frontend website.
It works for me.
