### ISSUE TITLE
Possible future issue with url structure

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#6]
Now one page is created for one day. If this calendar is used for let's say 3 years there might be 1000 pages in the same root.

https://forum.getkirby.com/t/server-response-time/279

> After lots of use cases with Kirby I can say that bottlenecks happen when you put a lot (like a couple hundred or even more than thousand) subpages in a single folder. That is when scanning the list of folders gets messy. Other than that Kirby can handle A LOT of content if it's structured more tree-ish.

**A possible solution to it would be like this:**

`[your-calendar-page]/y-2017/m-03/d-14`

It would be even nicer to have:

`[your-calendar-page]/2017/03/14` but Kirby does not like pages starting with a number.

As a bonus I could get all the events from a month without a problem. It would be harder with the current solution.

Thoughts?

**Comment by molocLab** [comment]
You are right, it's a performance issue to which I have already thought.

In the alpha version of calendar board there was an year folder between `[your-calendar-page]` and day page. I think it's enough to solve the issue, but I didn't add it in beta version because of this:

![download](https://cloud.githubusercontent.com/assets/11831276/12712234/3eeea13c-c8c7-11e5-8911-510b24abaae3.png)

I didn't find (yet) an elegant solution to visualize year and month pages in the panel.
List of months and list of day? I don't like that, I would prefer to keep the plugin as clean as possible, maybe hiding those breadcrumbs.

**Comment by jenstornell** [comment]
I don't think it's possible with the current version of the panel. You can add CSS to the panel but I don't see how it could match custom breadcrumb sub pages.

There is javascript but it can't be used outside the field.

Maybe the forum have some ideas.

I agree that the simplicity of the plugin is perfect as it is. I also love that it's possible to add whatever stuff to the day structure field. Genius.

**Comment by molocLab** [comment]
Another solution I thought about was to create a kind of auto-backup that every X years (or every X days created) moves (attention not deletes) a part of the folders outside the directory worlkflow.

Managing Calendar Board future events and activities past objects maybe aren't so important.

**Comment by jenstornell** [comment]
For daily usage the current version works best. For past events the year/month/day version works best.

Maybe have two setups? Always keep real data in a year/month/day folder strucure. Always keep new fresh data in the current setup until the data is 2 month old or so.

It feels a little risky. What if we need to look back at some data?

I don't have perfect idea here.

**Comment by jenstornell** [comment]
Another hackish solution could be to have a redirect field that redirect the pages that are year or month to the calendar. That way you would not need to design those pages.

It will not remove the main issue tho.

**Comment by molocLab** [comment]
You can hide useless breadcrumbs (year-xxxx, month-xxxx,...) using:
`ul.breadcrumb-list > li > a[title^="year-"]{display:none}`

Do I like it? Not so much. You have insert this rule in a panel css and call it through config.php resulting with "spaghettify" the plugin.

**Comment by jenstornell** [comment]
Ahh, yes, that would probably work.

Do I like it? In fact I think it's the best workaround so far, because the result of it ends up being exactly what we want, which is to not show the whole hierarchy in the breadcrumb.

I know that the panel will get alot of love this year by Bastian and I hope it means controlling it. Maybe it would be possible for blueprint to set their own breadcrumbs *yes I'm deaming now*.

**As I see it you have 3 choices:**

1. Do nothing and wait for the future. This means that everyone that uses this plugin will need some conversion process when the structure is changed. (I know you don't have a user storm right now)
1. Change the structure and use the css "hack" and add a real solution later. Then a conversion process will not be needed in the future.
1. Ask the forum for a solution that no one of us have thought of yet.

**Comment by molocLab** [comment]
Changed structure introducing year folder.
I've also added instruction to hide years breadcrumb.

I think it's enough for now.

**Comment by jenstornell** [comment]
It works, at least at the backend. Then it will work on the frontend as well. The content structure works as well. Close this task? Or are you not happy with this solution?
