### ISSUE TITLE
Different urls in the panel

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#7]
I don't know if it will be an issue as everything works but when clicking on a day I get this url:

`http://localhost/kirby2.2.3/panel/pages/projects/project-a/field/calendar/calendarboard/get-day/2016-02-04`

**When I use the breadcrumb I get this url:**

`http://localhost/kirby2.2.3/panel/pages/projects/project-a/year-2016/day-2016-02-04/edit`

Maybe just use the panel url? Or why do you link to a custom one?

**Comment by molocLab** [comment]
This is caused by the use of routes inside custom field.

**Comment by jenstornell** [comment]
Do you need a route? Can't you just link to `/year-2016/day-2016-02-04/edit` directly so the url matches the breadcrumb url??

**Comment by molocLab** [comment]
No, I can't link to that.

Calendar Board use basically 2 routes:

The first one is an ajax request made by arrows in calendar header.
The route used to shift the calendar month and load events without refreshing the page.

The second one is called when you click on a day cell: the route check if the year folder exist and the day folder exist (and in case it create them). After that the route redirect to` /year-2016/day-2016-02-04/edit` but the url in the address bar stays the same.

Routes related to a custom form field need to refer to field itself in the url to work, so I have to build the path in that way.

**Comment by jenstornell** [comment]
Ahh, now I see. You can use javascript history push state to manipulate the url to not make users like me confused.
