### ISSUE TITLE
Change date from inside?

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#8]
I just noticed that by changing the slug I can change the date. Nice!

However it would be more beautiful to change it with a field type date and with a hook update the date and then hide it?

Or leave it. I like the possiblility to change the date from inside a day.

![image](https://cloud.githubusercontent.com/assets/927011/12787222/be06a004-ca94-11e5-8af9-71ea0f632c1f.png)

**Comment by molocLab** [comment]
> I like the possiblility to change the date from inside a day

Me too. :)

**Comment by jenstornell** [comment]
"Me too" as in it will not be changed to a date field, but be left as it is?

**Comment by molocLab** [comment]
Yes
